name: hyperoct
channels:
  - pytorch
  - anaconda
  - dlr-sc
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cmake=3.19.6
  - coin-or-cbc=2.10.5
  - coin-or-cgl=0.60.3
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.6
  - coin-or-utils=2.11.4
  - configargparse=1.4
  - cryptography=39.0.1
  - cudatoolkit=11.2.72
  - cudatoolkit-dev=11.2.2
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.16
  - expat=2.4.4
  - flit-core=3.6.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freeimageplus=3.18.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - future=0.18.3
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.68.2
  - glog=0.4.0
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - imageio=2.26.0
  - importlib-metadata=6.0.0
  - intel-openmp=2022.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libssh2=1.10.0
  - libstdcxx-ng=9.5.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp=1.2.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.2
  - magma-cuda110=2.5.2
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2022.0.1
  - mkl-include=2023.0.0
  - mrc=0.2.1
  - multidict=5.2.0
  - munkres=1.1.4
  - ncurses=6.3
  - nibabel=5.0.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.1
  - openblas=0.3.12
  - openssl=1.1.1t
  - packaging=23.0
  - pcre=8.44
  - pillow=9.0.1
  - pip=23.0.1
  - protobuf=3.11.4
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rhash=1.4.1
  - rsa=4.7.2
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.5
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - tornado=6.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxcursor=1.2.0
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxinerama=1.1.4
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.11.0
  - zlib=1.2.12
  - zstd=1.4.5
  - pip:
    - scipy==1.10.1
    - setuptools==59.5.0
    - torch==1.9.0a0+gitunknown
